name: Pull Request Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore SDH/SDH.sln
    
    - name: Build
      run: dotnet build SDH/SDH.sln --no-restore
    
    - name: Test
      run: dotnet test SDH/SDH.sln --no-build --verbosity normal --logger trx --results-directory "TestResults"
    
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Tests
        path: TestResults/*.trx
        reporter: dotnet-trx